### ISSUE TITLE
Segfault on Python3.10/ Adding support for Python3.10

### ISSUE THREAD

**Issue by ValHayot** [mochi-hpc/py-mochi-margo#2]
Hi, I was wondering if it would be possible to add support for Python 3.10 as it currently segfaults during bulk transfers.
```
root@rdma:/py-mochi-margo# bash test.sh 
test_addr_copy (pymargo.test_addr.TestAddr) ... ok
test_addr_eql (pymargo.test_addr.TestAddr) ... ok
test_addr_str (pymargo.test_addr.TestAddr) ... ok
test_engine_addr (pymargo.test_addr.TestAddr) ... ok
test_ipull (pymargo.test_bulk.TestBulk) ... test.sh: line 8:  5452 Segmentation fault      (core dumped) python3 -m unittest --verbose
```

older versions of python (3.7.15 - 3.9.15) work just fine. Not quite sure which line of the Cython code is segfaulting, but can certainly look into it.

**Comment by mdorier** [comment]
Thanks for reporting this. I fixed the bug. It was cause by the default constructor of a `pybind11::bytes` object being called at a place where the python GIL was not held. Looks like it was OK for earlier versions of Python but not with 3.10.
I'll make a new patched release.
